name: exp_test_set_best_gen
collection_name: hse_test_set_best_gen
qdrant_host: localhost
qdrant_port: 6333
qdrant_path: data/qdrant_local_test_set_best_gen

preprocessing:
  lowercase: false
  remove_extra_whitespace: true
  remove_page_numbers: true
  remove_headers_footers: false

chunker:
  type: recursive
  size: 1200
  overlap: 200

embedder:
  type: sentence_transformer
  model: intfloat/multilingual-e5-base

retriever:
  type: dense
  top_k: 10

reranker:
  type: cross_encoder
  model: BAAI/bge-reranker-v2-m3
  top_k: 3

query_rewriter:
  model: gpt-4o-mini

generator:
  type: openai
  model: gpt-4o-mini
  temperature: 0.2
  max_tokens: 400
