name: exp_embedder_bge_m3
collection_name: hse_emb_bge_m3
qdrant_host: localhost
qdrant_port: 6333
qdrant_path: data/qdrant_local_bge_m3

preprocessing:
  lowercase: false
  remove_extra_whitespace: true
  remove_page_numbers: true
  remove_headers_footers: false

chunker:
  type: recursive
  size: 1200
  overlap: 200

embedder:
  type: sentence_transformer
  model: BAAI/bge-m3

retriever:
  type: dense
  top_k: 5

reranker:
  type: none

query_rewriter: {}

generator:
  type: none
