name: exp_reranker_minilm
collection_name: hse_rerank_minilm
qdrant_host: localhost
qdrant_port: 6333

preprocessing:
  lowercase: false
  remove_extra_whitespace: true
  remove_page_numbers: true
  remove_headers_footers: false

chunker:
  type: recursive
  size: 1200
  overlap: 200

embedder:
  type: sentence_transformer
  model: intfloat/multilingual-e5-base

retriever:
  type: dense
  top_k: 10

reranker:
  type: cross_encoder
  model: cross-encoder/ms-marco-MiniLM-L-6-v2
  top_k: 5

generator:
  type: none
