name: exp_chunking_sentence_1200
collection_name: hse_chunk_sentence_1200
qdrant_host: localhost
qdrant_port: 6333

preprocessing:
  lowercase: false
  remove_extra_whitespace: true
  remove_page_numbers: true
  remove_headers_footers: false

chunker:
  type: sentence
  size: 1200
  overlap: 200

embedder:
  type: sentence_transformer
  model: intfloat/multilingual-e5-base

retriever:
  type: dense
  top_k: 5

reranker:
  type: none

generator:
  type: none
