name: exp_chunking_recursive_800
collection_name: hse_chunk_recursive_800
qdrant_host: localhost
qdrant_port: 6333

preprocessing:
  lowercase: false
  remove_extra_whitespace: true
  remove_page_numbers: true
  remove_headers_footers: false

chunker:
  type: recursive
  size: 800
  overlap: 100

embedder:
  type: sentence_transformer
  model: intfloat/multilingual-e5-base

retriever:
  type: dense
  top_k: 5

reranker:
  type: none

generator:
  type: none
